"""add_roles_and_article_summaries

Revision ID: dae596d871e3
Revises: acbb4bcb3f7f
Create Date: 2026-03-30 02:05:01.777504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae596d871e3'
down_revision: Union[str, None] = 'acbb4bcb3f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('articles', sa.Column('what_is_it', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('why_it_matters', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('subscribers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscribers_role_id'), 'subscribers', ['role_id'], unique=False)
    op.create_foreign_key(None, 'subscribers', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_index(op.f('ix_subscribers_role_id'), table_name='subscribers')
    op.drop_column('subscribers', 'role_id')
    op.drop_column('articles', 'tags')
    op.drop_column('articles', 'why_it_matters')
    op.drop_column('articles', 'what_is_it')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
