"""add_signal_recommendations

Revision ID: d2ae745e451e
Revises: 9775ae125ac7
Create Date: 2026-03-30 03:50:58.676718+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ae745e451e'
down_revision: Union[str, None] = '9775ae125ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('suggested_state', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('acceleration_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_recommendations_id'), 'signal_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_signal_recommendations_status'), 'signal_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_signal_recommendations_topic_id'), 'signal_recommendations', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_recommendations_topic_id'), table_name='signal_recommendations')
    op.drop_index(op.f('ix_signal_recommendations_status'), table_name='signal_recommendations')
    op.drop_index(op.f('ix_signal_recommendations_id'), table_name='signal_recommendations')
    op.drop_table('signal_recommendations')
    # ### end Alembic commands ###
