"""add_is_published_to_topic

Revision ID: acbb4bcb3f7f
Revises: 326c3d98703f
Create Date: 2026-03-30 01:53:40.421324+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbb4bcb3f7f'
down_revision: Union[str, None] = '326c3d98703f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_url_key'), 'articles', type_='unique')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.drop_constraint(op.f('subscribers_email_key'), 'subscribers', type_='unique')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.add_column('topics', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('topics_name_key'), 'topics', type_='unique')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_unique_constraint(op.f('topics_name_key'), 'topics', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('topics', 'is_published')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_unique_constraint(op.f('subscribers_email_key'), 'subscribers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    op.create_unique_constraint(op.f('articles_url_key'), 'articles', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
